In [ ]:
import pandas as pd

In [ ]:
s = pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
s.values

array([10, 20, 30, 40, 50])

In [ ]:
s.dtype

dtype('int64')

In [ ]:
#indexing
s[0]

np.int64(10)

In [ ]:
s[0:4]

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
#iloc-> location based, only for the the int
s.iloc[3]

np.int64(40)

#changing the values
index = ["apple","banana","grapes","oranges","strawberry"]
s.index = index
s

In [ ]:
#loc -> label based indexing
s['banana':'strawberry']

banana        20
grapes        30
oranges       40
strawberry    50
dtype: int64

#dictionaries
fruit_protein = {
    "Avocado": 2.0,      # grams of protein
    "Guava": 2.6,
    "Blackberries": 2.0,
    "Oranges": 0.9,
    "Banana": 1.1,
    "Apples": 0.3,
    "Kiwi": 1.1,
    "Pomegranate": 1.7,
    "Mango": 0.8,
    "Cherries": 1.0
}

In [ ]:
fruit_protein = {
    "Avocado": 2.0,      # grams of protein
    "Guava": 2.6,
    "Blackberries": 2.0,
    "Oranges": 0.9,
    "Banana": 1.1,
    "Apples": 0.3,
    "Kiwi": 1.1,
    "Pomegranate": 1.7,
    "Mango": 0.8,
    "Cherries": 1.0
}

In [ ]:
s2 = pd.Series(fruit_protein, name = 'protien')
s

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: protien, dtype: float64

In [ ]:
#conditional selection , protien >1
s2[s2>1]

Avocado         2.0
Guava           2.6
Blackberries    2.0
Banana          1.1
Kiwi            1.1
Pomegranate     1.7
Name: protien, dtype: float64

In [ ]:
s2[(s2>0.5) &(s2<2)]

Oranges        0.9
Banana         1.1
Kiwi           1.1
Pomegranate    1.7
Mango          0.8
Cherries       1.0
Name: protien, dtype: float64

In [ ]:
#modifing
s2["mango"] = 2.8

In [ ]:
import numpy as np
ser = pd.Series(['a',np.nan,1,np.nan,2])
s.notnull().sum()

np.int64(10)

In [ ]:
#dataframe
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice'],
 'Age': [25, 30, 35, nan, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, nan, 50000]}

In [ ]:
#first 5 rows ->head , last 5 rows -> tail
df = pd.DataFrame(data)
df.head()

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN


df.tail()

In [ ]:
df[['Age','Department']]

    Age Department
0  25.0         HR
1  30.0         IT
2  35.0    Finance
3   NaN         IT
4  29.0         HR
5  25.0         HR

df.drop('Age', axis= 1, inplace = True, errors='ignore')
df

In [ ]:
df.shape

(6, 3)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Department  6 non-null      object
 2   Salary      5 non-null      float64
dtypes: float64(1), object(2)
memory usage: 276.0+ bytes

In [ ]:
df.describe()

             Salary
count      5.000000
mean   58400.000000
std     8532.291603
min    50000.000000
25%    50000.000000
50%    60000.000000
75%    62000.000000
max    70000.000000

In [ ]:
#broacasting
df["Salary"] = df["Salary"] +5000
df["Salary"]

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4        NaN
5    55000.0
Name: Salary, dtype: float64

In [ ]:
#rename
df.rename(columns = {"Department":"dept"}, inplace = True)
df

      Name     dept   Salary
0    Alice       HR  55000.0
1      Bob       IT  65000.0
2  Charlie  Finance  75000.0
3    David       IT  67000.0
4      Eve       HR      NaN
5    Alice       HR  55000.0

In [ ]:
df["Salary"].unique()

array([55000., 65000., 75000., 67000.,    nan])

In [ ]:
df["dept"].value_counts()

dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [ ]:
df["promted salary"] = df["Salary"] *10
df

      Name     dept   Salary  promted salary
0    Alice       HR  55000.0        550000.0
1      Bob       IT  65000.0        650000.0
2  Charlie  Finance  75000.0        750000.0
3    David       IT  67000.0        670000.0
4      Eve       HR      NaN             NaN
5    Alice       HR  55000.0        550000.0

In [ ]:
#data cleaning
df.isnull().sum()

Name              0
dept              0
Salary            1
promted salary    1
dtype: int64

In [ ]:
df.dropna(how = "any")#any row that had any null value

      Name     dept   Salary  promted salary
0    Alice       HR  55000.0        550000.0
1      Bob       IT  65000.0        650000.0
2  Charlie  Finance  75000.0        750000.0
3    David       IT  67000.0        670000.0
5    Alice       HR  55000.0        550000.0

In [ ]:
df.dropna(how = "all")#any row that had all null value

      Name     dept   Salary  promted salary
0    Alice       HR  55000.0        550000.0
1      Bob       IT  65000.0        650000.0
2  Charlie  Finance  75000.0        750000.0
3    David       IT  67000.0        670000.0
4      Eve       HR      NaN             NaN
5    Alice       HR  55000.0        550000.0

In [ ]:
# To make this cell executable independently and ensure 'Age' column exists for filling
import pandas as pd
import numpy as np

# Re-defining the original data
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}
df = pd.DataFrame(data)

# filling the 'Age' column
# The original code was df["Age"].fillna(df["Age"].mean())
# For a persistent change in df, inplace=True is commonly used
#mathametically
df["Age"].fillna(df["Age"].mean())
df["Age"]
df["Salary"].fillna(df["Salary"].median())
df["Salary"]
#filling random values -> forward fill , -> bakward fill
df["Age"].fillna(method = "ffill")
df["Age"].fillna(method = "bfill")

/tmp/ipykernel_5964/980722791.py:23: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "ffill")
/tmp/ipykernel_5964/980722791.py:24: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "bfill")

0    25.0
1    30.0
2    35.0
3    29.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
df["Name"].replace("Charlie","Roise")

0    Alice
1      Bob
2    Roise
3    David
4      Eve
5    Alice
Name: Name, dtype: object

In [ ]:
#deling with duplicate values
df_dup = df[df.duplicated(keep = "first")]
df_dup = df[df.duplicated(keep = "last")]
df_dup

    Name   Age Department   Salary
0  Alice  25.0         HR  50000.0

In [ ]:
df = df.drop_duplicates()
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN

In [ ]:
df["Salary"] = df["Salary"].apply(lambda x: x/10 if x > 6500000 else x )
df["Salary"]
#df[["first_name","last_name"]] = df["name"].str.split(_)
#apply , lambda
def muliply(x):
  return x*2

df["Age"] = df["Age"].apply(muliply)
df["Age"]

/tmp/ipykernel_5964/3228244541.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Salary"] = df["Salary"].apply(lambda x: x/10 if x > 6500000 else x )
/tmp/ipykernel_5964/3228244541.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Age"] = df["Age"].apply(muliply)

0    200.0
1    240.0
2    280.0
3      NaN
4    232.0
Name: Age, dtype: float64

#joins and merges
#joins -> left , right , outer , inner
#merges -> we will get both pd.concat
import pandas as pd
dataset1 = [12, 45, 78, 23, 56]
dataset2 = [34, 89, 15, 67, 42]
df1 = pd.DataFrame(dataset1)
df2 = pd.DataFrame(dataset2)
pd.concat([df1,df2], axis = 1)

In [ ]:
data = pd.read_csv("full_dataset.csv")
data.head()
data.shape
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   cpg_density         1000 non-null   float64
 1   genomic_location    1000 non-null   float64
 2   regulatory_score    1000 non-null   float64
 3   conservation_score  1000 non-null   float64
 4   methylation_status  1000 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 39.2 KB